### PR TITLE
Pull return into default case

### PR DESCRIPTION
**Pull request by cristaloleg**

### CODE REVIEW

**Comment by gobwas** [comment]
Are there any code style guides for doing so? )
If not, I prefer not to add additional line 😉

**Comment by cristaloleg** [comment]
It's very common when all switch cases have return statement and to pull return after into switch. Basically next function obey such rule 😉 https://github.com/gobwas/ws/pull/88/files#diff-404340f707ca89675cd4f32200b3a270L142

**Comment by cristaloleg** [comment]
Hm, strange fail https://travis-ci.org/gobwas/ws/jobs/589476026

**Comment by gobwas** [comment]
Looks like a racy test or racy connection termination for that test.

**Pull request merged**
