### PR TITLE
read result from OnHeader and OnRequest after Upgrader.Upgrade

### PR DESCRIPTION
**Pull request by joesonw**
This allows those who want to get things out of OnHeader&OnRequest handlers, without interferring with existing user.

### CODE REVIEW

**Comment by joesonw** [comment]
this should fix #31

**Comment by gobwas** [comment]
Hi! Thank you for the request.

Changes you suggest are violate the "zero-copy" idea of an Upgrader.

First, if you need the whole HTTP requests mapping you can use `UpgradeHTTP()` method and use standard lib `net/http` to handle requests. And it looks like you collecting all the headers in your request if `OnHeaderWithResult` is set.

Next, if you need to collect only subset of headers, you could do something like this in your application code:
```go
type Result struct {
    Header http.Header
    // ...
}

func Upgrade(conn net.Conn) (r Result, err error) {
    u := ws.Upgrader{
        OnHeader: func(key, value []byte) {
            if something {
                r.Header.Add(string(key), string(value))
            }
        },
    }
    _, err = u.Upgrade(conn)
    return r, err
}
```

**Comment by joesonw** [comment]
@gobwas  this means you have to construct a new upgrader for each request?

**Comment by gobwas** [comment]
Yes. Why it is a problem to construct an Upgrader for each request that will be allocated *on stack*? The only thing that can escape to heap in the example above is an `http.Header` instance which is a map actually; maps are always allocated on heap regardless of usage.

**Pull request closed without merging**
