### PR TITLE
OnTCP to server

### PR DESCRIPTION
**Pull request by DonsonGit**
Hello, I have a suggest for the repo. 
Here is some reason:

I use the ws to my project, it's very useful for me, buf there's some problem come out when the LB's health check request to my server, it all be responsed with 400 Bad request, and I have no idea how to deal with.

And I have no chance to deal the resquest before the error come up, so is there have any possible to deal the request before the error?

So I add the OnTCP to the server.go to provide a chance to customize the response.

Thank You.

### CODE REVIEW

**Comment by navossoc** [comment]
I think you can do that check with a zero-copy upgrade.

Do you have a minimal sample?

**Comment by gobwas** [comment]
Hey @DonsonGit,
There are few ways to solve your problem:
1. Use different TCP ports for healthchecks and WebSocket (preferable)
2. Use some heuristics for detecting that connection is a healthchecker instance (ip address subnet for example, or something like that)
3. If healthcheck comes with HTTP/1.1 and with GET, OnRequest() should work fine

All of that should work only if you use `ws.Upgrader`, and not the `ws.HTTPUpgrader` since that latter is used _after_ Go's standard http handler processed the request.

However if your load balancer really makes just TCP SYN checks, it should be happy since connection is established anyway.

**Comment by DonsonGit** [comment]
> I think you can do that check with a zero-copy upgrade.
> 
> Do you have a minimal sample?

Sorry for my late reply.

Here is my code now, and the "/" one is LB health check.
```
        ln, err := net.Listen("tcp", fmt.Sprintf(":%d", port))
	        if err != nil {
		       panic(err)
	        }

	healthResponse := ws.RejectConnectionError(
		ws.RejectionStatus(200))
	u := ws.Upgrader{
		OnTCP: func(method, uri []byte, major, minor int) error {

			if bytes.Equal(method, []byte(http.MethodHead)) && bytes.Equal(uri, []byte("/")) {
				return healthResponse
			}

			if bytes.Equal(method, []byte(http.MethodGet)) && bytes.Equal(uri, []byte("/ws")) {
				return nil
			}

			return ws.ErrHandshakeBadConnection
		},
	}

	for {
		conn, err := ln.Accept()
		if err != nil {
			panic(err)
		}

		_, err = u.Upgrade(conn)
		if err == healthResponse {
			continue
		}
		if err != nil {
			log.Println("upgrade err:", err)
			continue
		}
        }
```

If I use OnRequest or OnHost, I cannot even change the response of the request. If I read the content before upgrade, then I need to deal the conn by myself, it's complex.

**Comment by DonsonGit** [comment]
> Hey @DonsonGit,
> There are few ways to solve your problem:
> 
> 1. Use different TCP ports for healthchecks and WebSocket (preferable)
> 2. Use some heuristics for detecting that connection is a healthchecker instance (ip address subnet for example, or something like that)
> 3. If healthcheck comes with HTTP/1.1 and with GET, OnRequest() should work fine
> 
> All of that should work only if you use `ws.Upgrader`, and not the `ws.HTTPUpgrader` since that latter is used _after_ Go's standard http handler processed the request.
> 
> However if your load balancer really makes just TCP SYN checks, it should be happy since connection is established anyway.

Sorry for my late reply.

Thanks for your answer.

That's a good idea about the double port, but our ws servise is a old system, it is keep-alive 3 years until now, and I need to overhaul the system to get lower cost.

So I need to do that carefully, and I cannot change the other service.

**Pull request closed without merging**
